services:
  migrate:
    image: migrate/migrate
    networks:
      - internal
    volumes:
      - ./migrations:/migrations:ro
    secrets:
      - database_url
    entrypoint: >
      /bin/sh -c "
        export DATABASE_URL=$$(cat /run/secrets/database_url) &&
        migrate -path=/migrations -database=$$DATABASE_URL up
      "
    deploy:
      restart_policy:
        condition: none

secrets:
  database_url:
    external: true

networks:
  internal:
    external: true
