// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package sqlc

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, domain)
VALUES ($1, $2)
RETURNING id, domain, created_at
`

type CreateJobParams struct {
	ID     string
	Domain string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.ID, arg.Domain)
	var i Job
	err := row.Scan(&i.ID, &i.Domain, &i.CreatedAt)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, domain, created_at FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(&i.ID, &i.Domain, &i.CreatedAt)
	return i, err
}
