// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID           int32
	Domain       string
	Organization pgtype.Text
	Description  pgtype.Text
	Country      pgtype.Text
	City         pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type Contact struct {
	ID          int32
	CompanyID   int32
	Email       string
	FirstName   pgtype.Text
	LastName    pgtype.Text
	Position    pgtype.Text
	Department  pgtype.Text
	LinkedinUrl pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type Job struct {
	ID        string
	Domain    string
	CreatedAt pgtype.Timestamp
}

type JobResult struct {
	JobID     string
	CompanyID int32
}
