// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Result struct {
	JobID     string
	Company   string
	Email     pgtype.Text
	FetchedAt pgtype.Timestamp
}
