// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	GetCompanyByDomain(ctx context.Context, domain string) (Company, error)
	GetJob(ctx context.Context, id string) (Job, error)
	GetJobDetails(ctx context.Context, id string) ([]GetJobDetailsRow, error)
	LinkJobResult(ctx context.Context, arg LinkJobResultParams) error
	ListContactsByCompanyID(ctx context.Context, companyID int32) ([]Contact, error)
}

var _ Querier = (*Queries)(nil)
