// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Result struct {
	JobID     string           `json:"job_id"`
	Company   string           `json:"company"`
	Email     pgtype.Text      `json:"email"`
	FetchedAt pgtype.Timestamp `json:"fetched_at"`
}
