// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EmailForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-dark p-8 rounded-2xl shadow-2xl w-full max-w-md transition duration-500 transform hover:scale-[1.01] animate-fade-in\"><div class=\"flex justify-between items-center mb-6\"><h1 class=\"text-2xl font-bold text-primary dark:text-primary animate-fade-in-down\">Email Detector</h1></div><form hx-post=\"/submit\" hx-target=\"#result\" hx-swap=\"innerHTML transition:true\" class=\"space-y-4 animate-fade-in-up\"><input type=\"text\" name=\"company\" placeholder=\"e.g. Notion\" required class=\"w-full px-4 py-2 border border-muted dark:border-muted rounded-xl bg-white dark:bg-[#1a1a1a] text-black dark:text-light focus:ring-2 focus:ring-primary focus:outline-none transition-all duration-300\"> <button type=\"submit\" class=\"w-full py-2 px-4 bg-primary text-black font-semibold rounded-xl hover:bg-opacity-75 transition duration-300\">Detect Emails</button></form><div id=\"result\" class=\"mt-6 text-center text-sm text-muted dark:text-light animate-fade-in-up\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
