name: Deploy Renhance Stack

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: shahidshabbir-se

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and Push API Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: api-builder
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/renhance-api:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/renhance-api:${{ github.sha }}

      - name: Build and Push Worker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: worker-builder
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/renhance-worker:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/renhance-worker:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH with ed25519
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          echo -e "Host renhance-server\n  HostName ${{ secrets.SERVER_IP }}\n  User ${{ secrets.DEPLOY_USER }}\n  IdentityFile ~/.ssh/id_ed25519\n  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Package Migrations
        run: tar -czf migrations.tar.gz -C ./migrations .

      - name: Copy Migrations to Remote Server
        run: scp -o StrictHostKeyChecking=no migrations.tar.gz renhance-server:/tmp/migrations.tar.gz

      - name: Extract Migrations on Remote Server
        run: ssh renhance-server 'mkdir -p ~/renhance/migrations && tar -xzf /tmp/migrations.tar.gz -C ~/renhance/migrations'

      - name: Deploy Renhance Stack via SSH
        uses: cssnr/stack-deploy-action@v1
        with:
          name: renhance
          file: docker-stack.yaml
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_KEY }}

      - name: Wait for Database to Become Healthy
        run: |
          ssh renhance-server '
            echo "Waiting for PostgreSQL to be healthy..."
            for i in {1..10}; do
              docker inspect --format="{{json .State.Health.Status}}" $(docker ps -qf "name=postgres") | grep -q "healthy" && break
              echo "Still waiting..."
              sleep 5
            done
          '

      - name: Run Database Migrations
        run: |
          ssh renhance-server '
            export PGUSER=$$(cat /var/lib/docker/volumes/renhance_postgres_user/_data) &&
            export PGPASSWORD=$$(cat /var/lib/docker/volumes/renhance_postgres_password/_data) &&
            export PGDB=$$(cat /var/lib/docker/volumes/renhance_postgres_db/_data) &&
            docker run --rm \
              --network renhance_internal \
              -v ~/renhance/migrations:/migrations \
              migrate/migrate \
              -path=/migrations \
              -database "postgres://$$PGUSER:$$PGPASSWORD@db:5432/$$PGDB?sslmode=disable" \
              up
          '

      - name: Verify Deployment
        run: curl -f https://renhance.duckdns.org || exit 1
